/**
 * Author   : Jonathan Steven (yondercode@gmail.com)
 * License  : MIT
 */

import { generateFromSchema } from '../../src/typescript/generator'
import { dataTypes, northwind } from '../fixtures/standard'
import { writeResult } from '../utils'
import * as fs from 'fs'

describe('typescript generator', () => {
  test('generate datatypes', async () => {
    const expected1 = fs.readFileSync('./tests/fixtures/typescript/datatypes.ts').toString()
    const actual1 = await generateFromSchema(dataTypes, {
      formatterOptions: { semi: false },
      header:
        '/**\n * DataTypes TypeScript Interfaces\n * \n * This file is generated by Polymorph.js \n * Please do not edit\n */\n\n',
    })
    writeResult('./generated/datatypes.ts', actual1)
    expect(actual1).toBe(expected1)
  })

  test('generate northwind', async () => {
    const expected1 = fs.readFileSync('./tests/fixtures/typescript/northwind.ts').toString()
    const actual1 = await generateFromSchema(northwind)
    writeResult('./generated/northwind.ts', actual1)
    expect(actual1).toBe(expected1)
  })
})
