/**
 * DataTypes TypeScript Interfaces
 * 
 * This file is generated by Polymorph.js 
 * Please do not edit
 */

export interface Integers {
  col_bigint?: number
  col_boolean?: number
  col_boolean_alias_1?: number
  col_int?: number
  col_int_alias_1?: number
  /**
   * Integer with 5 digit length
   */
  col_int_len?: number
  col_mediumint?: number
  col_smallint?: number
  col_tinyint?: number
  /**
   * Unsigned 64 bit integer
   */
  col_ubigint?: number
  /**
   * Unsigned 32 bit integer
   */
  col_uint?: number
}

export interface Floats {
  col_double?: number
  col_double_alias_1?: number
  col_double_alias_2?: number
  col_float?: number
}

export interface Decimals {
  col_decimal?: string
  col_decimal_alias_1?: string
  col_decimal_alias_2?: string
  col_decimal_alias_3?: string
  col_decimal_precision?: string
}

export interface Time {
  col_date?: Date
  col_datetime?: Date
  col_datetime_ms?: Date
  col_datetime_us?: Date
  col_time?: Date
  col_timestamp?: Date
  col_timestamp_ms?: Date
  col_timestamp_us?: Date
  col_year?: Date
}

export interface Strings {
  col_char?: string
  col_char_alias_1?: string
  col_char_alias_2?: string
  col_enum?: "ONE" | "TWO" | "THREE"
  col_json?: string
  col_longtext?: string
  col_mediumtext?: string
  col_set?: ("ONE" | "TWO" | "THREE")[]
  col_text?: string
  col_tinytext?: string
  col_varchar?: string
  col_varchar_alias_1?: string
  col_varchar_alias_2?: string
}

export interface Binaries {
  col_binary?: Buffer[]
  col_bit?: Buffer[]
  col_blob?: Buffer[]
  col_longblob?: Buffer[]
  col_mediumblob?: Buffer[]
  col_tinyblob?: Buffer[]
  col_varbinary?: Buffer[]
}

export interface Spatials {
  col_geometry?: any
  col_geometrycollection?: any[]
  col_linestring?: any
  col_multilinestring?: any[]
  col_multipoint?: any[]
  col_multipolygon?: any[]
  col_point?: any
  col_polygon?: any
}

export interface Defaults {
  col_auto_increment: number
  col_current_time_on_create: Date
  col_current_time_on_update: Date
  col_filler?: string
  col_varchar_default: string
}

